#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_ROOT="${MELKAPOW_FRONTEND_OUT_ROOT:-$ROOT_DIR}"
TARGET_FILE="$OUT_ROOT/assets/js/runtime-config.js"
ENV_FILE="$ROOT_DIR/app/.env"

api_base="${MELKAPOW_API_BASE:-${API_BASE_URL:-}}"

if [ -z "$api_base" ] && [ -f "$ENV_FILE" ]; then
  raw_line=""
  for key in MELKAPOW_API_BASE API_BASE_URL; do
    raw_line="$(awk -v k="$key" '$0 ~ "^[[:space:]]*(export[[:space:]]+)?" k "[[:space:]]*=" {print; exit}' "$ENV_FILE" || true)"
    if [ -n "$raw_line" ]; then
      break
    fi
  done
  if [ -n "$raw_line" ]; then
    api_base="${raw_line#*=}"
    api_base="$(printf "%s" "$api_base" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"

    # Strip quotes + inline comments (best-effort .env parsing).
    if [ -n "$api_base" ]; then
      first="${api_base:0:1}"
      if [ "$first" = "\"" ]; then
        api_base="${api_base#\"}"
        api_base="${api_base%%\"*}"
      elif [ "$first" = "'" ]; then
        api_base="${api_base#\'}"
        api_base="${api_base%%\'*}"
      else
        # Only treat `# ...` as a comment when it has a leading space.
        api_base="$(printf "%s" "$api_base" | sed -E 's/[[:space:]]+#.*$//')"
      fi
    fi
  fi
fi

api_base="$(printf "%s" "$api_base" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//; s#/+$##')"
escaped_api_base="${api_base//\\/\\\\}"
escaped_api_base="${escaped_api_base//\"/\\\"}"

mkdir -p "$(dirname "$TARGET_FILE")"
cat > "$TARGET_FILE" <<EOF
// Generated by scripts/generate-runtime-config.sh
window.MELKAPOW_RUNTIME_CONFIG = window.MELKAPOW_RUNTIME_CONFIG || {};
window.MELKAPOW_RUNTIME_CONFIG.MELKAPOW_API_BASE = "$escaped_api_base";
window.MELKAPOW_RUNTIME_CONFIG.API_BASE_URL = "$escaped_api_base";
EOF

printf "Wrote %s (MELKAPOW_API_BASE=%s)\n" "$TARGET_FILE" "${api_base:-<empty>}"
